version: '3.8'

services:
  app:
    build: ../target/docker/stage/
    image: todo-ar-project:1.0.0
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - default
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=ar
      - POSTGRES_PASSWORD=ar-todo
      - POSTGRES_DB=ar
    ports:
      - "5432:5432"
    networks:
      - default
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/scripts.sql
      - db:/var/lib/postgresql15/data

volumes:
  db:
    driver: local

networks:
  default:
    driver: bridge