version: '3.8'

services:
  app:
    build: target/docker/stage/
    image: todo-ar-project:1.0.0
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: postgres:15
    restart: always
    volumes:
      - ".db/sql:/docker-entrypoint-initdb.d"
    environment:
      - "POSTGRES_USER=ar"
      - "POSTGRES_PASSWORD=ar-todo"
      - "POSTGRES_DB=ar-project"
    ports:
      - "5432:5432"

volumes:
  db:
    driver: local
